---
name: ansible-lint
'on': [push, pull_request]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ansible Lint
        uses: ansible/ansible-lint-action@v6.16.0
