---
name: ansible-lint
'on': [push, pull_request]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.15.0
