---
name: yaml-lint
'on': [push, pull_request]

jobs:
  build:
    name: YAML Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: ansible-role-cloudflared/.yamllint
